### PR TITLE
{ deps: Array<string>, callback: Function } and add auto-prefix by `:…

### PR DESCRIPTION
**Pull request by bluelovers**
…`; (Step: 1)

Step: 1

[ M] modified - Changes not staged for commit:

	src/index.ts

### CODE REVIEW

**Comment by DSchau** [comment]
@bluelovers Could you describe (and possibly add some documentation to README.md) as to what this is actually doing, and the benefits to it?

**Comment by bluelovers** [comment]
`gulp.task(name, deps, callback);`

=

```
{
	name: {
		deps: [
			':c',
		],
		callback: callback,
	}
}
```

`:c` will become same treelevel of name

we can use this without add parent name

**Comment by DSchau** [comment]
@bluelovers OK, so could you provide a use case or an example of how this is valuable? The callback makes sense, and I can see the utility of that, but I am unsure of how deps is helpful.

It would help me understand if you edit README.md with this new functionality, so that I can better understand it

**Comment by bluelovers** [comment]
https://github.com/bluelovers/node-gw2plus/blob/master/gulp-task/arcdps.ts

**Comment by DSchau** [comment]
I think this library and what you're intended it to be used for are for different purposes. Rather than setting a dependency (`:c`), I would recommend that you simply make another gulp task, and then use this task as an array item in the task list.

In your example, I would make two gulp tasks (I'd recommend calling them something more descriptive than `c` and/or `d`).

To make `d` dependent on `c`, you would use addTasks like so:

const gulp = require('gulp');
const addTasks = require('gulp-add-tasks')(gulp);

// add c and d here

```javascript
addTasks({
build: {
    description: 'Build application for distribution',
    tasks: [
      'c',
      'd' // d will be run after c completes
    ],
    options: {
      production: 'Minify assets with this flag'
    }
  }
});
```

**Comment by bluelovers** [comment]
or maybe should allow use function at tasks list?

like tasks: [ 'c', 'd', a_task_function]

**Comment by DSchau** [comment]
When you register a gulp task, i.e. `gulp.task('some-task', function() {})` it's inherently registered as a function (and thus callable via the tasks array).

I think that's cleaner, otherwise we're getting outside gulp. I'd prefer to continue to leverage gulp when we can

**Comment by bluelovers** [comment]
but that will make a task will become never should call it, only can call by other task already dep order

**Comment by bluelovers** [comment]
does this a little better?
https://github.com/bluelovers/gulp-add-tasks/blob/master/test

**Pull request closed without merging**
